version = 0.1
[default.deploy.parameters]
stack_name = "stack-employee-management-appsync-poc-test"
resolve_s3 = true
region = "ap-south-1"
profile = "iamadmin-management"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_prefix = "stack-employee-management-appsync-poc-test"
parameter_overrides = "LogLevel=\"INFO\""
